server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
    
  zipkin:
      base-url: http://localhost:9411/zipkin/
      
  cloud:
    gateway:
      routes:
      - id: MASTERDATA-SERVICE
        uri: lb://MASTERDATA-SERVICE
        predicates:
          - Path=/olx/masterdata/**
      - id: ADVERTISE-SERVICE
        uri: lb://ADVERTISE-SERVICE
        predicates:
          - Path=/olx/advertise/**
          
      - id: LOGIN-SERVICE
        uri: lb://LOGIN-SERVICE
        predicates:
          - Path=/olx/user/**
    
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
