server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: login-service

  zipkin:
    base-url: http://localhost:9411
  config:
    import: configserver:http://localhost:8888
  
  data:
     mongodb:
      host: localhost
      port: 27017
      database: logintokendb
    
    
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true