server:
  port: 9001

spring:
  application:
    name: advertise-service
  config:
    import: configserver:http://localhost:8888
  zipkin:
    base-url: http://localhost:9411

management:
   endpoints:
     web:
       exposure:
         include: "*"
   health:
     circuitbreakers:
       enabled: true
   endpoint:
     health:
       show-details: always
       
resilience4j:
  circuitbreaker:
    instances:
        # All Category cuircuit breaker
      ALL-CATEGORIES-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        
        # Category cuircuit breaker
      CATEGORY-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        
        # ALL-STATUS cuircuit breaker
      ALL-STATUS-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        
        # STATUS cuircuit breaker
      STATUS-CIRCUIT_BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreashold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s