server:
  port: 9003
  
spring:
    application:
      name: masterdata-service
    zipkin:
      base-url: http://localhost:9411/zipkin/
      
    config:
      import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
            
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true